accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('training_plans/', views.TrainingPlansListView.as_view(), name='training_plans'),
    path('training_plan/<uuid:pk>/', views.TrainingPlanDetailView.as_view(), name='training_plan_detail'),
    path('add_exercise/<uuid:pk>/', views.add_exercise, name='add_exercise'),
    path('delete_exercise/<uuid:pk>/<str:exercise_name>/', views.delete_exercise, name='delete_exercise'),
    path('training_schedule/<uuid:pk>/', views.TrainingScheduleDetailView.as_view(), name='training_schedule_detail'),
    path('get-target-activities/<uuid:pk>/', views.GetTrainingScheduleAnalysisView.as_view(), name='get-target-activities'),
    path('record_strength_activity/<uuid:pk>/', views.RecordStrengthActivityView.as_view(), name='record_strength_activity'),
    path('record_isometric_activity/<uuid:pk>/', views.RecordIsometricActivityView.as_view(), name='record_isometric_activity'),
    path('record_cardio_activity/<uuid:pk>/', views.RecordCardioActivityView.as_view(), name='record_cardio_activity'),
    path('exercise_detail/<uuid:pk>/', views.ExerciseDetailView.as_view(), name='exercise_detail'),
    path('training_plan_create', views.TrainingPlanCreateView.as_view(), name='create_training_plan'),
    path('training_schedule_create', views.TrainingScheduleCreateView.as_view(), name='create_training_schedule'),
    path('help', views.HelpView.as_view(), name='help'),
    path('create_exercise', views.ExerciseCreateView.as_view(), name='create_exercise'),
    path('exercise_list', views.ExerciseListView.as_view(), name='exercise_list'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
import calendar
import datetime 
import uuid

from django.db.models import JSONField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

from src import settings



class Muscle(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    CHOICES = (
        ('Chest', 'Chest'),
        ('Back', 'Back'),
        ('Legs', 'Legs'),
        ('Glutes', 'Glutes'),
        ('Arms', 'Arms'),
        ('Shoulders', 'Shoulders'),
        ('Core', 'Core'),
        ('Full Body', 'Full Body'),#
    )
    muscle_group = models.CharField(max_length=150, choices=CHOICES)

    class Meta:
        ordering = ['muscle_group', 'name']
        
    def __str__(self):
        return f"{self.name} ({self.muscle_group})"
    
class Equipment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'equipment'
        
    def __str__(self):
        return self.name
    
class Exercise(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)
    primary_muscle_focus = models.ForeignKey(Muscle, related_name='primary_exercises', on_delete=models.CASCADE)
    secondary_muscle_focus = models.ForeignKey(Muscle, related_name='secondary_exercises', on_delete=models.CASCADE, blank=True, null=True)
    equipment = models.ManyToManyField(Equipment, blank=True)
    CHOICES = (
        ('Cardio', 'Cardio'),
        ('Strength', 'Strength'),
        ('Isometric', 'Isometric'),
    )
    type = models.CharField(max_length=50, choices=CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Created by"
        )

    class Meta:
        ordering = ['type', 'name']
        
    
    def get_absolute_url(self):
        return reverse('exercise_detail', args=[str(self.id)])
        
    def __str__(self):
        return self.name
    
    
class Activity(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    athlete = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Executed by"
        )
    
class StrengthActivity(Activity):
    reps = models.IntegerField()
    weight = models.IntegerField()
    
    class Meta:
        ordering = ['-date', 'exercise']
        verbose_name_plural = 'Strength activities'
        
    def __str__(self):
        return f"Strength activity for {self.exercise.name} - {self.reps} reps - {self.weight} kg"
    
class IsometricActivity(Activity):
    duration = models.IntegerField(help_text="Duration in seconds")
    
    class Meta:
        ordering = ['-date', 'exercise']
        verbose_name_plural = 'Isometric activities'
        
    def __str__(self):
        return f"Isometric activity for {self.exercise.name} - {self.duration} seconds hold"
    
class CardioActivity(Activity):
    duration = models.IntegerField(help_text="Duration in seconds")
    
    class Meta:
        ordering = ['-date', 'exercise']
        verbose_name_plural = 'Cardio activities'
        
    def __str__(self):
        return f"Cardio activity for {self.exercise.name} - {self.duration} seconds"

class TrainingPlan(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150, help_text="Name of the training plan.")
    description = models.TextField(help_text="Description of the training plan that covers the main object of the plan.")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Created by"
        )
    exercises = JSONField(blank=True, null=True)
    
    class Meta:
        ordering = ['name']
        
    def get_absolute_url(self):
        return reverse('training_plan_detail', args=[str(self.id)])
    
    def __str__(self):
        return self.name
    
class TrainingSchedule(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    athlete = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    notes = models.TextField(blank=True, null=True, help_text="Add any additional notes for the training schedule if you wish to do so")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    training_plan = models.ForeignKey(TrainingPlan, on_delete=models.CASCADE, help_text="Select the training plan to be used for the training schedule")
    start_date = models.DateField(help_text="Start date of the training schedule")
    duration = models.PositiveIntegerField(help_text="Duration in weeks")
    CHOICES = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),    
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),    
        ('Sunday', 'Sunday'),
    )
    train_on_mondays = models.BooleanField(default=False, help_text="Decide whether Monday shall be a training day")
    train_on_tuesdays = models.BooleanField(default=False, help_text="Decide whether Tuesday shall be a training day")
    train_on_wednesdays = models.BooleanField(default=False, help_text="Decide whether Wednesday shall be a training day")
    train_on_thursdays = models.BooleanField(default=False, help_text="Decide whether Thursday shall be a training day")
    train_on_fridays = models.BooleanField(default=False, help_text="Decide whether Friday shall be a training day")
    train_on_saturdays = models.BooleanField(default=False, help_text="Decide whether Saturday shall be a training day")
    train_on_sundays = models.BooleanField(default=False, help_text="Decide whether Sunday shall be a training day")
    target_activities = JSONField(blank=True, null=True)
    actual_activities = JSONField(blank=True, null=True)
    
    def get_training_week(self, date:datetime.date) -> int:
        """Function that returns the training week number based on the start date and the given date"""
        if date < self.start_date or date > self.end_date:
            raise ValueError("Given date is outside the training schedule")
        
        delta = date - self.start_date
        return delta.days // 7 + 1
    
    def _add_target_activities(self):
        """Function that adds the target activities for the entire duration of the training schedule based on the exercises of the underlying training plan"""
        if self.target_activities is None:
            self.target_activities = dict()
            
        delta = datetime.timedelta(days=1)
        current_date = self.start_date
        while current_date <= self.end_date:
            if not self.is_training_day(current_date):
                # not a training day
                target = dict()
                for exercise_name in self.training_plan.exercises.keys():
                    target[exercise_name] = [0, 0]
                self.target_activities[current_date.isoformat()] = target
            else:
                # training day
                target = dict()
                training_week = self.get_training_week(current_date)
                for exercise_name, values in self.training_plan.exercises.items():
                    starting_reps = values[0]
                    repetition_progression_per_week = values[1]
                    target_reps = starting_reps + (training_week - 1) * repetition_progression_per_week
                    starting_weight = values[2]
                    weight_progression_per_week = values[3]
                    target_weight = starting_weight + (training_week - 1) * weight_progression_per_week
                    target[exercise_name] = [target_reps, target_weight]
                self.target_activities[current_date.isoformat()] = target
            
            current_date += delta
        
        self.save()
        
    def get_target_activity_absolute(self, date:datetime.date, exercise_name:str) -> list:
        """Function that returns the target repetitions/duration and weight for the given date and exercise"""
        if exercise_name not in self.training_plan.exercises.keys():
            return [0, 0]
        
        if date < self.start_date or date > self.end_date:
            raise ValueError("Given date is outside the training schedule")
        
        return self.target_activities[date.isoformat()][exercise_name]
    
    def get_actual_activity_absolute(self, date:datetime.date, exercise_name:str) -> list:
        """Function that returns the actual repetitions/duration and weight for the given date and exercise"""
        
        if self.actual_activities is not None and date.isoformat() in self.actual_activities.keys():
            if exercise_name not in self.actual_activities[date.isoformat()].keys():
                return [0, 0]
            return self.actual_activities[date.isoformat()][exercise_name]
        
        return [0, 0]
    
    def get_target_repetitions_cumulative(self, date:datetime.date, exercise_name:str) -> list:

app/templates/add_exercise.html
{% for exercise in exercises %}
<div>{{ exercise }}</div>
{% endfor %}

app/templates/cardio_activity_create.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section>
  <div class="container">
    <h1>Record cardio activity</h1>
    <form method="POST" action="{% url 'record_cardio_activity' training_schedule.pk %}">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</section>
{% endblock %}

app/templates/exercise_create.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="my-5">
  <div class="container">
    <h1>Create a new exercise</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
</section>
{% endblock %}

app/templates/exercise_detail.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <h1 class="display-4">{{ exercise.name }}</h1>
      {% if exercise.description %}
        <p class="lead text-secondary">{{ exercise.description }}</p>
      {% else %}
        <p class="lead text-secondary">No description available</p>
      {% endif %}
      <hr class="my-4">
      <h2>Primary muscle focus</h2>
      <p class="text-secondary">{{ exercise.primary_muscle_focus }}</p>
      <h2>Secondary muscle focus</h2>
      <p class="text-secondary">{% if exercise.secondary_muscle_focus %}{{ exercise.secondary_muscle_focus }}{% else %}No secondary muscle focus{% endif %}</p>
      <h2>Equipment</h2>
      {% if exercise.equipment.all %}
        {% if exercise.equipment.all|length > 1 %}
        <ul>
          {% for item in exercise.equipment.all %}
          <li class="text-secondary">{{ item }}</li>
          {% endfor %}
        </ul>
        {% else %}
        <p class="text-secondary">{{ exercise.equipment.all.first }}</p>
        {% endif %}
      {% else %}
      <p class="text-secondary">No equipment needed</p>
      {% endif %}
      <h2>Exercise type</h2>
      <p class="text-secondary">{{ exercise.type }}</p>
    </div>
  </div>
</div>
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <h2>Similar exercises</h2>
      {% if similar_exercises %}
      <ul>
        {% for exercise in similar_exercises %}
        <li><a href="{{ exercise.get_absolute_url }}">{{ exercise.name }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <p class="text-secondary">No similar exercises found</p>
      {% endif %}
    </div>
  </div>
</div>
<div class="container pb-5">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <h2>Other exercises</h2>
      {% if other_exercises %}
      <ul>
        {% for exercise in other_exercises %}
        <li><a href="{{ exercise.get_absolute_url }}">{{ exercise.name }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <p class="text-secondary">No other exercises found</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/exercise_list.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="my-5">
  <div class="container">
    <h1><i class="fas fa-book"></i> Exercises</h1>
    <div class="text-secondary">Below you will find a list of all available exercises. If you would like to create an additional exercise that you cannot find in the list then please go ahead and <a href="{% url 'create_exercise' %}">create a new exercise.</a></div>
    <hr>
    {% for exercise in exercises %}
    <div class="my-4">
      <div class="h3 fw-bold"><a href="{{ exercise.get_absolute_url }}">{{ exercise.name }}</a></div>
      <div class="text-secondary">{{ exercise.description }}</div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

app/templates/home.html
{% extends 'base_generic.html' %}
{% block content %}
<div class="container my-5">
  {% if user.is_authenticated %}
  <div class="text-end">
    <a href="{% url 'create_training_schedule' %}" class="btn btn-primary">
      <i class="fas fa-plus"></i> New Training Schedule
    </a>
  </div>
  <h1 class="mt-5 mb-2"><i class="fas fa-calendar"></i> My Training Schedules</h1>
  <div class="text-secondary">A Training Schedule is your personalized implementation of a Training Plan. You will be required to do the exercises of the Training Plan including the target repetitions, weight, progression per week etc. but you can decide when you want to start, for how many weeks you want to follow the Training Plan and most importantly on how many and on which days you want to train. Before you create your own Training Schedule be sure to know on which Training Plan you want to base it on. Have a look at <a href="{% url 'training_plans' %}">our Training Plans.</a></div>
  <hr>
  {% if training_schedules %}
  <div class="row">
    {% for training_schedule in training_schedules %}
    <div class="col-12 col-md-3">
      <div class="card text-center bg-black text-white border">
        <div class="card-header bg-dark">{{ training_schedule.start_date|date:"d.m.y" }} - {{ training_schedule.end_date|date:"d.m.y" }}</div>
        <div class="card-body">
          <div class="h3 fw-bold">{{ training_schedule.duration }} weeks</div>
          <div>based on</div>
          <div><a href="{{ training_schedule.training_plan.get_absolute_url }}">'{{ training_schedule.training_plan.name }}'</a></div>
        </div>
        <hr class="mb-0">
        <div class="card-footer"><a href="{{ training_schedule.get_absolute_url }}"
            class="btn btn-outline-secondary btn-sm">Details</a></div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>You have no training schedules</p>
  {% endif %}
  {% else %}
  <div class="text-center mt-5">
    <p class="fw-bold">Please login or signup to continue</p>
    <a href="{% url 'login' %}" class="btn btn-success">Login</a>
    <a href="{% url 'accounts:signup' %}" class="btn btn-outline-secondary">Signup</a>
  </div>
  {% endif %}
</div>

{% endblock %}

app/templates/isometric_activity_create.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section>
  <div class="container">
    <h1>Record isometric activity</h1>
    <form method="POST" action="{% url 'record_isometric_activity' training_schedule.pk %}">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</section>
{% endblock %}

app/templates/strength_activity_create.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section>
  <div class="container">
    <h1>Record strength activity</h1>
    <form method="POST" action="{% url 'record_strength_activity' training_schedule.pk %}">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</section>
{% endblock %}

app/templates/target_vs_actual.html
{{ trainingschedule.end_date }}
{% if date_warning %}
<div class="alert alert-warning mt-0 my-5" role="alert">Attention: the selected date ({{ date|date:"d F y" }}) is outside the planned training schedule</div>
</div>
{% endif %}
<h3 class="fw-bold">Target vs. Actual (absolute)</h3>
<div class="table-responsive">
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Exercise</th>
        <th class="text-center" scope="col">Target Reps/Duration</th>
        <th class="text-center" scope="col">Target Weight</th>
        <th class="text-center" scope="col">Actual Reps/Duration</th>
        <th class="text-center" scope="col">Actual Weight</th>
        <th class="text-center" scope="col">Gap Reps/Duration</th>
        <th class="text-center" scope="col">Gap Weight</th>
      </tr>
    </thead>
    <tbody>
      {% for exercise, values in target_vs_actual_absolute.items %}
      <tr>
        <td><a href="{{ exercise.get_absolute_url }}">{{ exercise.name }}</a></td>
        <td class="text-center {% if values.0.0 < 0 %}text-danger{% endif %}">{{ values.0.0|floatformat:"0" }}</td>
        <td class="text-center {% if values.0.1 < 0 %}text-danger{% endif %}">{{ values.0.1|floatformat:"-1" }}</td>
        <td class="text-center {% if values.1.0 < 0 %}text-danger{% endif %}">{{ values.1.0|floatformat:"0" }}</td>
        <td class="text-center {% if values.1.1 < 0 %}text-danger{% endif %}">{{ values.1.1|floatformat:"-1" }}</td>
        <td class="text-center {% if values.2.0 < 0 %}text-danger{% endif %}">{{ values.2.0|floatformat:"-1" }}</td>
        <td class="text-center {% if values.2.1 < 0 %}text-danger{% endif %}">{{ values.2.1|floatformat:"-1" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<h3 class="fw-bold mt-5">Target vs. Actual (cumulative)</h3>
<div class="table-responsive">
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Exercise</th>
        <th class="text-center" scope="col">Target Reps/Duration</th>
        <th class="text-center" scope="col">Actual Reps/Duration</th>
        <th class="text-center" scope="col">Gap Reps/Duration</th>
      </tr>
    </thead>
    <tbody>
      {% for exercise_name, values in target_vs_actual_cumulative.items %}
      <tr>
        <td>{{ exercise_name }}</td>
        <td class="text-center {% if values.0 < 0 %}text-danger{% endif %}">{{ values.0|floatformat:"0" }}</td>
        <td class="text-center {% if values.1 < 0 %}text-danger{% endif %}">{{ values.1|floatformat:"0" }}</td>
        <td class="text-center {% if values.2 < 0 %}text-danger{% endif %}">{{ values.2|floatformat:"-1" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

app/templates/test.html
<div class="table-responsive">
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Exercise</th>
        <th class="text-center" scope="col">Starting Repetitions</th>
        <th class="text-center" scope="col">Repetition Progression per Week</th>
        <th class="text-center" scope="col">Starting Weight</th>
        <th class="text-center" scope="col">Weight Progression per Week</th>
      </tr>
    </thead>
    <tbody>
      {% for key, value in trainingplan.exercises.items %}
      <tr>
        <td>{{ key }}</td>
        <td class="text-center">{{ value.0|floatformat:"-1" }}</td>
        <td class="text-center">{{ value.1|floatformat:"-1" }}</td>
        <td class="text-center">{{ value.2|floatformat:"-1" }}</td>
        <td class="text-center">{{ value.3|floatformat:"-1" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

app/templates/training_plan_detail.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
  <h1><i class="fas fa-dumbbell"></i> {{ trainingplan.name }}</h1>
  <p>{{ trainingplan.description }}</p>
  <hr>
  <div id="exercises-list">
    {% if trainingplan.exercises %}
    {% include 'snippet_tp_exercises.html' %}
    {% else %}
    <p class="text-secondary">No exercises have been added to the training plan yet</p>
    {% endif %}
  </div>
</div>
<div class="container my-4">
  {% if request.user == trainingplan.author %}
  <div class="row align-items-center justify-content-between">
      <div class="col-12 col-md-12 py-3 ps-3 shadow rounded">
        <form method="post" hx-post="{% url 'add_exercise' trainingplan.pk %}" hx-target="#exercises-list"
          hx-trigger="submit" hx-boost="true">
          {% csrf_token %}
          <div class="row">
            <div class="col-12">
              {{ form.exercise|as_crispy_field }}
            </div>
            <div class="col-md-4">
              {{ form.starting_repetitions|as_crispy_field }}
              {{ form.repetition_progression_per_week|as_crispy_field }}
            </div>
            <div class="col-md-4">
              {{ form.starting_weight|as_crispy_field }}
              {{ form.weight_progression_per_week|as_crispy_field }}
            </div>
          </div>
          <div class="text-end">
            <button type="submit" class="btn btn-success">Add Exercise</button>
          </div>
        </form>
      </div>
  </div>
  <div class="my-5">You can't find the exercise you are looking for? Go ahead and just <a href="{% url 'create_exercise' %}">create a new exercise.</a></div>
  {% else %}
  <p class="text-secondary">You cannot adjust this training plan as you are not the creator.</p>
  {% endif %}
</div>
{% endblock %}

app/templates/training_plans_list.html
{% extends 'base_generic.html' %}
{% block content %}
<div class="container mt-5">
  <div class="text-end">
    <a href="{% url 'create_training_plan' %}" class="btn btn-primary">
      <i class="fas fa-plus"></i> Create Training Plan
    </a>
  </div>
  <h1 class="mt-5"><i class="fas fa-dumbbell"></i> Training Plans</h1>
  <div class="text-secondary">Below you will find a list of all available Training Plans. Take a look at some of them. If you like one you can start a new Training Schedule based on that Training Plan or you can create your own Training Plan. A Training Schedule is your personalized implementation of a Training Plan. You will be required to do the exercises of the Training Plan including the target repetitions, weight, progression per week etc. but you can decide when you want to start, for how many weeks you want to follow the Training Plan and most importantly on how many and on which days you want to train. So, if you have found your favorite Training Plan then go ahead and <a href="{% url 'create_training_schedule' %}">create your own personalized Training Schedule.</a></div>
  <hr>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for trainingplan in trainingplan_list %}
    <div class="col">
      <div class="card bg-dark text-white h-100">
        <div class="card-header h3 fw-bold"><a href="{{ trainingplan.get_absolute_url }}" class="text-white">{{ trainingplan.name }}</a></div>
        <div class="card-body">{{ trainingplan.description }}</div>
        <div class="card-footer">{{ trainingplan.exercises|length }} exercises</div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/training_schedule_create.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="my-5">
  <div class="container">
    <h1>Create a new training schedule</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
</section>
{% endblock %}